/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_25 (coord M15), LPUART1_RXD/J32[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_RXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_RXD_SIGNAL                                    RXD   /*!< Signal name */

/* GPIO_AD_24 (coord L13), LPUART1_TXD/J31[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART1_TXD_PERIPHERAL                            LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART1_TXD_SIGNAL                                    TXD   /*!< Signal name */

/* GPIO_EMC_B2_18 (coord N3), USER_GREEN */
/* Routed pin properties */
#define BOARD_INITPINS_USER_GREEN_PERIPHERAL                               GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_USER_GREEN_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_GREEN_CHANNEL                                    28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_GREEN_GPIO                                     GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_GREEN_GPIO_PIN                                   28U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_GREEN_GPIO_PIN_MASK                      (1U << 28U)   /*!< GPIO pin mask */

/* GPIO_AD_08 (coord R15), USER_RED */
/* Routed pin properties */
#define BOARD_INITPINS_USER_RED_PERIPHERAL                                 GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_USER_RED_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_RED_CHANNEL                                       7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_RED_GPIO                                       GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_RED_GPIO_PIN                                      7U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_RED_GPIO_PIN_MASK                         (1U << 7U)   /*!< GPIO pin mask */

/* GPIO_AD_10 (coord R17), USER_BLUE */
/* Routed pin properties */
#define BOARD_INITPINS_USER_BLUE_PERIPHERAL                                GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_USER_BLUE_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_BLUE_CHANNEL                                      9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_BLUE_GPIO                                      GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_BLUE_GPIO_PIN                                     9U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_BLUE_GPIO_PIN_MASK                        (1U << 9U)   /*!< GPIO pin mask */

/* WAKEUP (coord T8), USER_S1 */
/* Routed pin properties */
#define BOARD_INITPINS_USER_S1_PERIPHERAL                                 GPIO13   /*!< Peripheral name */
#define BOARD_INITPINS_USER_S1_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_USER_S1_CHANNEL                                        0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_USER_S1_GPIO                                       GPIO13   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_USER_S1_GPIO_PIN                                       0U   /*!< GPIO pin number */
#define BOARD_INITPINS_USER_S1_GPIO_PIN_MASK                          (1U << 0U)   /*!< GPIO pin mask */

/* GPIO_AD_34 (coord J16), 1588_EVENT0_IN/SD1_VSELECT */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_VSELECT_PERIPHERAL                             USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_VSELECT_SIGNAL                          usdhc_vselect   /*!< Signal name */

/* GPIO_SD_B1_00 (coord B16), SD1_CMD/J15[3]/WIFI_SDIO_CMD/J54[11]/NVCC_SD/U19G[D14] */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_CMD_PERIPHERAL                                 USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_CMD_SIGNAL                                  usdhc_cmd   /*!< Signal name */

/* GPIO_SD_B1_01 (coord D15), SD1_CLK/J15[5]/WIFI_SDIO_CLK/J54[9] */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_CLK_PERIPHERAL                                 USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_CLK_SIGNAL                                  usdhc_clk   /*!< Signal name */

/* GPIO_SD_B1_02 (coord C15), SD1_D0/J15[7]/WIFI_SDIO_D0/J54[13]/NVCC_SD/U19G[D14] */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_D0_PERIPHERAL                                  USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_D0_SIGNAL                                  usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_SD1_D0_CHANNEL                                         0U   /*!< Signal channel */

/* GPIO_SD_B1_03 (coord B17), SD1_D1/J15[8]/WIFI_SDIO_D1/J54[15] */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_D1_PERIPHERAL                                  USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_D1_SIGNAL                                  usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_SD1_D1_CHANNEL                                         1U   /*!< Signal channel */

/* GPIO_SD_B1_04 (coord B15), SD1_D2/J15[1]/WIFI_SDIO_D2/J54[17] */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_D2_PERIPHERAL                                  USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_D2_SIGNAL                                  usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_SD1_D2_CHANNEL                                         2U   /*!< Signal channel */

/* GPIO_SD_B1_05 (coord A16), SD1_D3/J15[2]/WIFI_SDIO_D3/J54[19] */
/* Routed pin properties */
#define BOARD_INITPINS_SD1_D3_PERIPHERAL                                  USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD1_D3_SIGNAL                                  usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_SD1_D3_CHANNEL                                         3U   /*!< Signal channel */

/* GPIO_AD_35 (coord G17), 1588_EVENT0_OUT/SD_PWREN_B */
/* Routed pin properties */
#define BOARD_INITPINS_SD_PWREN_B_PERIPHERAL                              GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_SD_PWREN_B_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SD_PWREN_B_CHANNEL                                     2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SD_PWREN_B_GPIO                                    GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SD_PWREN_B_GPIO_PIN                                    2U   /*!< GPIO pin number */
#define BOARD_INITPINS_SD_PWREN_B_GPIO_PIN_MASK                       (1U << 2U)   /*!< GPIO pin mask */

/* GPIO_AD_32 (coord K16), ENET_MDC/U7[12]/SD1_CD_B/J15[9] */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_MDC_PERIPHERAL                             CM7_GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_MDC_SIGNAL                           gpio_mux_io_cm7   /*!< Signal name */
#define BOARD_INITPINS_ENET_MDC_CHANNEL                                      31U   /*!< Signal channel */

/* GPIO_DISP_B2_10 (coord D9), LPUART2_TXD/BT_UART_TXD/U354[4]/U16[2]/J25[3]/J9[4] */
/* Routed pin properties */
#define BOARD_INITPINS_BT_UART_TXD_PERIPHERAL                             LPI2C3   /*!< Peripheral name */
#define BOARD_INITPINS_BT_UART_TXD_SIGNAL                                    SCL   /*!< Signal name */

/* GPIO_DISP_B2_11 (coord A6), LPUART2_RXD/BT_UART_RXD/U16[3]/U355[20]/J9[2] */
/* Routed pin properties */
#define BOARD_INITPINS_BT_UART_RXD_PERIPHERAL                             LPI2C3   /*!< Peripheral name */
#define BOARD_INITPINS_BT_UART_RXD_SIGNAL                                    SDA   /*!< Signal name */

/* GPIO_EMC_B1_41 (coord L1), SEMC_CSX0/U14A[C6] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_CSX0_PERIPHERAL                              LPUART6   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_CSX0_SIGNAL                                      RXD   /*!< Signal name */

/* GPIO_EMC_B1_40 (coord K1), SEMC_RDY/U14A[C8] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_RDY_PERIPHERAL                               LPUART6   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_RDY_SIGNAL                                       TXD   /*!< Signal name */

/* GPIO_LPSR_05 (coord N8), I2C5_SCL/J48[27]/U32[17]/U34[4]/J10[20] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C5_SCL_PERIPHERAL                                LPI2C5   /*!< Peripheral name */
#define BOARD_INITPINS_I2C5_SCL_SIGNAL                                       SCL   /*!< Signal name */

/* GPIO_LPSR_04 (coord N7), I2C5_SDA/J48[26]/U32[18]/U34[6]/J10[18] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C5_SDA_PERIPHERAL                                LPI2C5   /*!< Peripheral name */
#define BOARD_INITPINS_I2C5_SDA_SIGNAL                                       SDA   /*!< Signal name */

/* GPIO_LPSR_07 (coord R8), I2C6_SCL/J50[12] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C6_SCL_PERIPHERAL                                LPI2C6   /*!< Peripheral name */
#define BOARD_INITPINS_I2C6_SCL_SIGNAL                                       SCL   /*!< Signal name */

/* GPIO_LPSR_06 (coord P8), I2C6_SDA/J50[11] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C6_SDA_PERIPHERAL                                LPI2C6   /*!< Peripheral name */
#define BOARD_INITPINS_I2C6_SDA_SIGNAL                                       SDA   /*!< Signal name */

/* GPIO_EMC_B2_11 (coord L4), SEMC_D26/U25[45] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D26_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D26_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D26_CHANNEL                                      21U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D26_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D26_GPIO_PIN                                     21U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D26_GPIO_PIN_MASK                        (1U << 21U)   /*!< GPIO pin mask */

/* GPIO_AD_09 (coord R16), CAM_PWR_EN */
/* Routed pin properties */
#define BOARD_INITPINS_DSI_RST_PERIPHERAL                                  GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_DSI_RST_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DSI_RST_CHANNEL                                        8U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DSI_RST_GPIO                                        GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DSI_RST_GPIO_PIN                                       8U   /*!< GPIO pin number */
#define BOARD_INITPINS_DSI_RST_GPIO_PIN_MASK                          (1U << 8U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_12 (coord M2), CAM_SPARE */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D27_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D27_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D27_CHANNEL                                      22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D27_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D27_GPIO_PIN                                     22U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D27_GPIO_PIN_MASK                        (1U << 22U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

/* GPIO_AD_29 (coord M17), DSI_EN */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_DSI_EN_PERIPHERAL                          GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_DSI_EN_SIGNAL                            gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_DSI_EN_CHANNEL                               28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_DSI_EN_GPIO                                GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_DSI_EN_GPIO_PIN                              28U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_DSI_EN_GPIO_PIN_MASK                 (1U << 28U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_00 (coord K2), LPI2C2_SCL */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_LPI2C2_SCL_PERIPHERAL                     LPI2C2   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_LPI2C2_SCL_SIGNAL                            SCL   /*!< Signal name */

/* GPIO_EMC_B2_01 (coord K4), LPI2C2_SDA */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_LPI2C2_SDA_PERIPHERAL                     LPI2C2   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_LPI2C2_SDA_SIGNAL                            SDA   /*!< Signal name */

/* GPIO_AD_30 (coord K17), DSI_TS_INT */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_DSI_TS_INT_PERIPHERAL                      GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_DSI_TS_INT_SIGNAL                        gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_DSI_TS_INT_CHANNEL                           29U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_DSI_TS_INT_GPIO                            GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_DSI_TS_INT_GPIO_PIN                          29U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_DSI_TS_INT_GPIO_PIN_MASK             (1U << 29U)   /*!< GPIO pin mask */

/* GPIO_AD_05 (coord P13), DSI_TS_RST */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_DSI_TS_RST_PERIPHERAL                      GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_DSI_TS_RST_SIGNAL                        gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_DSI_TS_RST_CHANNEL                            4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_DSI_TS_RST_GPIO                            GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_DSI_TS_RST_GPIO_PIN                           4U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_DSI_TS_RST_GPIO_PIN_MASK              (1U << 4U)   /*!< GPIO pin mask */

/* GPIO_AD_15 (coord M14), LCD_RST_B */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_LCD_RST_B_PERIPHERAL                       GPIO9   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_LCD_RST_B_SIGNAL                         gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_LCD_RST_B_CHANNEL                            14U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_LCD_RST_B_GPIO                             GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_LCD_RST_B_GPIO_PIN                           14U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_LCD_RST_B_GPIO_PIN_MASK              (1U << 14U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_03 (coord R1), DSI_BL_PWM */
/* Routed pin properties */
#define BOARD_INITMIPIPANELPINS_DSI_BL_PWM_PERIPHERAL                      GPIO8   /*!< Peripheral name */
#define BOARD_INITMIPIPANELPINS_DSI_BL_PWM_SIGNAL                        gpio_io   /*!< Signal name */
#define BOARD_INITMIPIPANELPINS_DSI_BL_PWM_CHANNEL                           13U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITMIPIPANELPINS_DSI_BL_PWM_GPIO                            GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITMIPIPANELPINS_DSI_BL_PWM_GPIO_PIN                          13U   /*!< GPIO pin number */
#define BOARD_INITMIPIPANELPINS_DSI_BL_PWM_GPIO_PIN_MASK             (1U << 13U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitMipiPanelPins(void);           /* Function assigned for the Cortex-M7F */

/* GPIO_LPSR_09 (coord P5), DMIC_DATA0/U41[5]/J50[20]/LPSPI6_CS0/J26[11] */
/* Routed pin properties */
#define BOARD_INITPINS_PDM_DMIC_DATA0_PERIPHERAL                             MIC   /*!< Peripheral name */
#define BOARD_INITPINS_PDM_DMIC_DATA0_SIGNAL                       mic_bitstream   /*!< Signal name */
#define BOARD_INITPINS_PDM_DMIC_DATA0_CHANNEL                                 0U   /*!< Signal channel */

/* GPIO_LPSR_10 (coord R5), JTAG_nTRST/J1[3]/LPSPI6_SCK /J26[9]/DMIC_DATA1 */
/* Routed pin properties */
#define BOARD_INITPINS_PDM_DMIC_DATA1_PERIPHERAL                             MIC   /*!< Peripheral name */
#define BOARD_INITPINS_PDM_DMIC_DATA1_SIGNAL                       mic_bitstream   /*!< Signal name */
#define BOARD_INITPINS_PDM_DMIC_DATA1_CHANNEL                                 1U   /*!< Signal channel */

/* GPIO_LPSR_08 (coord U8), DMIC_CLK/U41[1]/U44[1]/J50[18] */
/* Routed pin properties */
#define BOARD_INITPINS_PDM_DMIC_CLK_PERIPHERAL                               MIC   /*!< Peripheral name */
#define BOARD_INITPINS_PDM_DMIC_CLK_SIGNAL                                   CLK   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins_Pdm(void);                /* Function assigned for the Cortex-M7F */

/* GPIO_EMC_B2_04 (coord M1), SEMC_D20/U25[8] */
/* Routed pin properties */
#define BOARD_INITPINS_SAI_SEMC_D20_PERIPHERAL                              SAI2   /*!< Peripheral name */
#define BOARD_INITPINS_SAI_SEMC_D20_SIGNAL                              sai_mclk   /*!< Signal name */

/* GPIO_EMC_B2_08 (coord P1), SEMC_DM2/U25[15] */
/* Routed pin properties */
#define BOARD_INITPINS_SAI_SEMC_DM2_PERIPHERAL                              SAI2   /*!< Peripheral name */
#define BOARD_INITPINS_SAI_SEMC_DM2_SIGNAL                           sai_tx_data   /*!< Signal name */

/* GPIO_EMC_B2_10 (coord R2), SEMC_D25/U25[44] */
/* Routed pin properties */
#define BOARD_INITPINS_SAI_SEMC_D25_PERIPHERAL                              SAI2   /*!< Peripheral name */
#define BOARD_INITPINS_SAI_SEMC_D25_SIGNAL                           sai_tx_sync   /*!< Signal name */

/* GPIO_EMC_B2_09 (coord N2), SEMC_D24/U25[42] */
/* Routed pin properties */
#define BOARD_INITPINS_SAI_SEMC_D24_PERIPHERAL                              SAI2   /*!< Peripheral name */
#define BOARD_INITPINS_SAI_SEMC_D24_SIGNAL                           sai_tx_bclk   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins_Sai(void);                /* Function assigned for the Cortex-M7F */

/* GPIO_EMC_B2_19 (coord U2), ENET_RGMII_MDC */
/* Routed pin properties */
#define BOARD_INITENETPINS_ENET_RGMII_MDC_PERIPHERAL                        ENET   /*!< Peripheral name */
#define BOARD_INITENETPINS_ENET_RGMII_MDC_SIGNAL                        enet_mdc   /*!< Signal name */

/* GPIO_EMC_B2_20 (coord R3), ENET_RGMII_MDIO */
/* Routed pin properties */
#define BOARD_INITENETPINS_ENET_RGMII_MDIO_PERIPHERAL                       ENET   /*!< Peripheral name */
#define BOARD_INITENETPINS_ENET_RGMII_MDIO_SIGNAL                      enet_mdio   /*!< Signal name */

/* GPIO_DISP_B2_02 (coord E9), ENET_TXD0/U7[24]/BT_CFG[8] */
/* Routed pin properties */
#define BOARD_INITENETPINS_ENET_TXD0_PERIPHERAL                             ENET   /*!< Peripheral name */
#define BOARD_INITENETPINS_ENET_TXD0_SIGNAL                           enet_tdata   /*!< Signal name */
#define BOARD_INITENETPINS_ENET_TXD0_CHANNEL                                  0U   /*!< Signal channel */

/* GPIO_DISP_B2_03 (coord D7), ENET_TXD1/U7[25]/BT_CFG[9] */
/* Routed pin properties */
#define BOARD_INITENETPINS_ENET_TXD1_PERIPHERAL                             ENET   /*!< Peripheral name */
#define BOARD_INITENETPINS_ENET_TXD1_SIGNAL                           enet_tdata   /*!< Signal name */
#define BOARD_INITENETPINS_ENET_TXD1_CHANNEL                                  1U   /*!< Signal channel */

/* GPIO_DISP_B2_04 (coord C7), ENET_TXEN/U7[23]/BT_CFG[10] */
/* Routed pin properties */
#define BOARD_INITENETPINS_ENET_TXEN_PERIPHERAL                             ENET   /*!< Peripheral name */
#define BOARD_INITENETPINS_ENET_TXEN_SIGNAL                           enet_tx_en   /*!< Signal name */

/* GPIO_DISP_B2_05 (coord C9), ENET_TX_REF_CLK/U7[9]/BT_CFG[11] */
/* Routed pin properties */
#define BOARD_INITENETPINS_ENET_TX_REF_CLK_PERIPHERAL                       ENET   /*!< Peripheral name */
#define BOARD_INITENETPINS_ENET_TX_REF_CLK_SIGNAL                   enet_ref_clk   /*!< Signal name */

/* GPIO_DISP_B2_06 (coord C6), ENET_RXD0/U7[16] */
/* Routed pin properties */
#define BOARD_INITENETPINS_ENET_RXD0_PERIPHERAL                             ENET   /*!< Peripheral name */
#define BOARD_INITENETPINS_ENET_RXD0_SIGNAL                           enet_rdata   /*!< Signal name */
#define BOARD_INITENETPINS_ENET_RXD0_CHANNEL                                  0U   /*!< Signal channel */

/* GPIO_DISP_B2_07 (coord D6), ENET_RXD1/U7[15] */
/* Routed pin properties */
#define BOARD_INITENETPINS_ENET_RXD1_PERIPHERAL                             ENET   /*!< Peripheral name */
#define BOARD_INITENETPINS_ENET_RXD1_SIGNAL                           enet_rdata   /*!< Signal name */
#define BOARD_INITENETPINS_ENET_RXD1_CHANNEL                                  1U   /*!< Signal channel */

/* GPIO_DISP_B2_08 (coord B5), ENET_CRS_DV/U7[18] */
/* Routed pin properties */
#define BOARD_INITENETPINS_ENET_CRS_DV_PERIPHERAL                           ENET   /*!< Peripheral name */
#define BOARD_INITENETPINS_ENET_CRS_DV_SIGNAL                         enet_rx_en   /*!< Signal name */

/* GPIO_DISP_B2_09 (coord D8), ENET_RXER/U7[20] */
/* Routed pin properties */
#define BOARD_INITENETPINS_ENET_RXER_PERIPHERAL                             ENET   /*!< Peripheral name */
#define BOARD_INITENETPINS_ENET_RXER_SIGNAL                           enet_rx_er   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitEnetPins(void);                /* Function assigned for the Cortex-M7F */

/* GPIO_DISP_B1_00 (coord E13), ENET_RGMII_RX_EN/U10[26] */
/* Routed pin properties */
#define BOARD_INITENET1GPINS_ENET_RGMII_RX_EN_PERIPHERAL                 ENET_1G   /*!< Peripheral name */
#define BOARD_INITENET1GPINS_ENET_RGMII_RX_EN_SIGNAL                  enet_rx_en   /*!< Signal name */

/* GPIO_DISP_B1_01 (coord D13), ENET_RGMII_RXC/U10[27] */
/* Routed pin properties */
#define BOARD_INITENET1GPINS_ENET_RGMII_RXC_PERIPHERAL                   ENET_1G   /*!< Peripheral name */
#define BOARD_INITENET1GPINS_ENET_RGMII_RXC_SIGNAL                   enet_rx_clk   /*!< Signal name */

/* GPIO_DISP_B1_02 (coord D11), ENET_RGMII_RXD0/U10[25] */
/* Routed pin properties */
#define BOARD_INITENET1GPINS_ENET_RGMII_RXD0_PERIPHERAL                  ENET_1G   /*!< Peripheral name */
#define BOARD_INITENET1GPINS_ENET_RGMII_RXD0_SIGNAL                   enet_rdata   /*!< Signal name */
#define BOARD_INITENET1GPINS_ENET_RGMII_RXD0_CHANNEL                          0U   /*!< Signal channel */

/* GPIO_DISP_B1_03 (coord E11), ENET_RGMII_RXD1/U10[24] */
/* Routed pin properties */
#define BOARD_INITENET1GPINS_ENET_RGMII_RXD1_PERIPHERAL                  ENET_1G   /*!< Peripheral name */
#define BOARD_INITENET1GPINS_ENET_RGMII_RXD1_SIGNAL                   enet_rdata   /*!< Signal name */
#define BOARD_INITENET1GPINS_ENET_RGMII_RXD1_CHANNEL                          1U   /*!< Signal channel */

/* GPIO_DISP_B1_04 (coord E10), ENET_RGMII_RXD2/U10[23] */
/* Routed pin properties */
#define BOARD_INITENET1GPINS_ENET_RGMII_RXD2_PERIPHERAL                  ENET_1G   /*!< Peripheral name */
#define BOARD_INITENET1GPINS_ENET_RGMII_RXD2_SIGNAL                   enet_rdata   /*!< Signal name */
#define BOARD_INITENET1GPINS_ENET_RGMII_RXD2_CHANNEL                          2U   /*!< Signal channel */

/* GPIO_DISP_B1_05 (coord C11), ENET_RGMII_RXD3/U10[22] */
/* Routed pin properties */
#define BOARD_INITENET1GPINS_ENET_RGMII_RXD3_PERIPHERAL                  ENET_1G   /*!< Peripheral name */
#define BOARD_INITENET1GPINS_ENET_RGMII_RXD3_SIGNAL                   enet_rdata   /*!< Signal name */
#define BOARD_INITENET1GPINS_ENET_RGMII_RXD3_CHANNEL                          3U   /*!< Signal channel */

/* GPIO_DISP_B1_06 (coord D10), ENET_RGMII_TXD3/U10[15]/BT_CFG[0] */
/* Routed pin properties */
#define BOARD_INITENET1GPINS_ENET_RGMII_TXD3_PERIPHERAL                  ENET_1G   /*!< Peripheral name */
#define BOARD_INITENET1GPINS_ENET_RGMII_TXD3_SIGNAL                   enet_tdata   /*!< Signal name */
#define BOARD_INITENET1GPINS_ENET_RGMII_TXD3_CHANNEL                          3U   /*!< Signal channel */

/* GPIO_DISP_B1_07 (coord E12), ENET_RGMII_TXD2/U10[16]/BT_CFG[1] */
/* Routed pin properties */
#define BOARD_INITENET1GPINS_ENET_RGMII_TXD2_PERIPHERAL                  ENET_1G   /*!< Peripheral name */
#define BOARD_INITENET1GPINS_ENET_RGMII_TXD2_SIGNAL                   enet_tdata   /*!< Signal name */
#define BOARD_INITENET1GPINS_ENET_RGMII_TXD2_CHANNEL                          2U   /*!< Signal channel */

/* GPIO_DISP_B1_08 (coord A15), ENET_RGMII_TXD1/U10[17]/BT_CFG[2] */
/* Routed pin properties */
#define BOARD_INITENET1GPINS_ENET_RGMII_TXD1_PERIPHERAL                  ENET_1G   /*!< Peripheral name */
#define BOARD_INITENET1GPINS_ENET_RGMII_TXD1_SIGNAL                   enet_tdata   /*!< Signal name */
#define BOARD_INITENET1GPINS_ENET_RGMII_TXD1_CHANNEL                          1U   /*!< Signal channel */

/* GPIO_DISP_B1_09 (coord C13), ENET_RGMII_TXD0/U10[18]/BT_CFG[3] */
/* Routed pin properties */
#define BOARD_INITENET1GPINS_ENET_RGMII_TXD0_PERIPHERAL                  ENET_1G   /*!< Peripheral name */
#define BOARD_INITENET1GPINS_ENET_RGMII_TXD0_SIGNAL                   enet_tdata   /*!< Signal name */
#define BOARD_INITENET1GPINS_ENET_RGMII_TXD0_CHANNEL                          0U   /*!< Signal channel */

/* GPIO_DISP_B1_10 (coord B14), ENET_RGMII_TX_EN/U10[19]/BT_CFG[4] */
/* Routed pin properties */
#define BOARD_INITENET1GPINS_ENET_RGMII_TX_EN_PERIPHERAL                 ENET_1G   /*!< Peripheral name */
#define BOARD_INITENET1GPINS_ENET_RGMII_TX_EN_SIGNAL                  enet_tx_en   /*!< Signal name */

/* GPIO_DISP_B1_11 (coord A14), ENET_RGMII_TXC/U10[20]/BT_CFG[5] */
/* Routed pin properties */
#define BOARD_INITENET1GPINS_ENET_RGMII_TXC_PERIPHERAL                   ENET_1G   /*!< Peripheral name */
#define BOARD_INITENET1GPINS_ENET_RGMII_TXC_SIGNAL                enet_tx_clk_io   /*!< Signal name */

/* GPIO_AD_16 (coord N17), SPDIF_OUT/WIFI_RST_B/U354[3] */
/* Routed pin properties */
#define BOARD_INITENET1GPINS_SPDIF_OUT_PERIPHERAL                        ENET_1G   /*!< Peripheral name */
#define BOARD_INITENET1GPINS_SPDIF_OUT_SIGNAL                           enet_mdc   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitEnet1GPins(void);              /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
