/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeIDE
 * @brief     STM32CubeIDE System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the newlib libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the ST_LICENSE file
 * in the root directory of this software component.
 * If no ST_LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>

// Currently malloc is not supported
#if 0
static uint8_t *__sbrk_heap_end = NULL;
void *_sbrk(ptrdiff_t incr)
{
  extern uint8_t __HeapBase; /* Symbol defined in the linker script */
  extern uint8_t __HeapLimit; /* Symbol defined in the linker script */
  uint8_t *prev_heap_end;
  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end) {
    __sbrk_heap_end = &__HeapBase;
  }

  incr = (incr + 7) & (~7); // align value to 8
  /* Protect heap from growing into the reserved MSP stack */
  if (__sbrk_heap_end + incr > &__HeapLimit) {
    errno = ENOMEM;
    return (void *)-1;
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end += incr;

  return (void *)prev_heap_end;
}
#endif
